dist: xenial
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: "__token__"
  on:
    tags: true
    distributions: sdist bdist_wheel
  password:
    secure: G5k9NifzzkL+2pox+h8XGdrIj/Qr6a+eXBMtdifkWxgAau1jQwNisWCkc7eCqDAgdBDk6tChuLS2wTls+5/UvH6RMNR+BqxPZK9c+Pm+D+N0uMx/TDlFfC9o/TMG8Juar4CWHYyfK2uRczT2TQ8jqY6UoDjedW2D6yzKDf4P5iZwQwXwlWbYaJlc6SryZ5WM4iln/GqVk0MU3k590EX9eytaHB0arTOuqacqTHo7qBmCvpgLXWLtPwckFPw+dSk6FMoRKGRl1d5ag2RvylZVA5ycgYQtD78JViHzdRK5/QqdOlRGZZFxfMznOPLxL75Es8ySWZ+QAiTNxh1OzexynPXKyL+MBYSbv3ecFRXffj+pQfQzxRy0hE0C/nnMm02I9zVY1DrY6Be320hwPcY71caYhCTaK/U9h6eO/vbqSWI4GRM+47eWwHmlJmXhHAdy88MChTO4ALvt4FIJ2fgPx2NOKm5iIdIQft/wDrF/03ynas3xfryRAMCi+NWiW64IOYTBXprRNhSjgGL6Q9nIKoqePXAf8ES6KQZSNhITAoWvp34dSfcjl+EBTKdLEG8byel72E2SacvZTiCEeYI7JqDx6RDs3sZsV2HHszGd9je213MpNRrc+I9MbcoA73ilYuXwBgc6MQQeD8q4Yp3eStlzRNm5wgbaScfPIBj3VnY=
