#This is an example. The model here is a simplification of an existing one.

modelName: EACS #URI: https://w3id.org/okn/i/mint/EACS
modelVersion: v7 #URI: https://w3id.org/okn/i/mint/EACS_v7
#configuration with no setup ->is modelConfig. Setup is model setup
configuration: EACS_v7_ethiopia
#short_name maps to label. I think it's easier to understand
short_name: Basic configuration of the economic aggregate crop supply model (EACS) v2 
description:
- Aggregate crop supply response model for the country of South Sudan (version 2)
author:
- name: Rajiv Mayani  #Assume type is person unless a type:Organization is added. 
contributor: #optional
- name:  Deborah Khider
- name: Zeya Zhang
  email: blah@b.com
hasComponentLocation:
- https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/economic-v2/economic-v2.zip
hasImplementationScriptLocation: #Optional
- https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/economic-v2/run
keywords:
- economy; land use; crop production; fertilizer costs
hasGrid: #optional
- short_name:  Grid from the economic crop supply model
  description:
  - Grid from the economic crop supply model
  hasDimension:  0D
  hasShape:  Point
  hasSpatialResolution:  Point
hasModelCategory: #optional
- Economy
hasRegion: #Optional
- description:
  - Area of the Pongo Basin in South Sudan
  short_name: Pongo basin region (South Sudan)
hasSoftwareImage: mintproject/economic:v2
hasSourceCode: #optional
- codeRepository: https://github.com/mintproject/MINT-WorkflowDomain/tree/master/WINGSWorkflowComponents/economic-v2
  description:
  - Code for creating an encapsulation of EACS for a model configuration (version 2)
  short_name: EACS configuration component (version 2 of code)
  programmingLanguage:
  - shell
hasOutputTimeInterval:
- short_name: Simple economic time interval
  description:
  - Time interval used in the aggregate crop supply response model for the country
    of South Sudan configuration
  
hasProcess: #each has to be mapped to an object.
  - Supply of Crop
  - Use of Fertilizer
  - Use of land
hasInput:
#input1
- short_name: economic-sim #start always with the name of the input/output/param
  description: #should always follow the short name
  - Contains the economic data used in the simulation analysis
  position: 1
  type: #By default these are all datasetSpecifications. The type below is an additional aid
  - https://w3id.org/wings/export/MINT#EconomicSimData
  hasDimensionality: 0 #If this is not specified, assume 0
  hasFormat: csv
  variables: #Maps to hasPresentation. The information about presentations should appear last
  - short_name: c1
    description:
    - costs of production per unit land area
    hasLongName: land cost
    hasShortName: c1
    hasStandardName: land_crop__production_cost-per-area #maps to hasStandardVariable + standard Name.
    #Let's assume this is a string. We'll have to convert it to an object. 
    usesUnit: USD ha-1 
#input2
- short_name: economic-subsidies
  description:
  - File indicating the economic subsidies to use on each iteration of the model
  hasDimensionality: 0
  hasFormat: txt
  position: 2
  type:
  - https://w3id.org/wings/export/MINT#EconomicSubsidies
  variables: 
  - short_name: c2
    description:
    - costs of production per unit land area example
    hasLongName: land cost example
    hasStandardName: land_crop__production_cost-per-area_example
    usesUnit: USD ha-1 

hasOutput:
#output 1
- short_name: crop-yield
  description:
  - Contains the yield elasticities to fertilizer use that are derived from Cycles
    output
  hasDimensionality: 0
  hasFormat: csv
  position: 1
  type:
  - https://w3id.org/wings/export/MINT#CropYield
  variables:
  - short_name: eta
    description:
    - Econ Eta
  - short_name: c2
    description:
    - Econ C2
  - short_name: p
    description:
    - Econ P
    
  #output 2
- short_name: economic-data
  description:
  - Contains data on observed prices for each crop and supply elasticities and the
    costs of production for each crop
  position: 2
  type:
  - https://w3id.org/wings/export/MINT#EconomicData

hasParameter:
- short_name: maize-crop-price-adjustment
  description:
  - Change in market price by crop
  usesUnit: "%"
  dataType: float #maps to hasDataType
  defaultvalue: 0 #maps to hasDefaultValue
  maxValue: 50 #optional. Maps to hasMaximumAcceptedValue
  minValue: -50 #optional. Maps to hasMinimumAcceptedValue 
  

